name: Conditional tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.16'

    - name: Install dependencies
      run: go mod tidy

    - name: Determine persistent flag
      id: determine-persistent
      run: |
        if grep -q "var persistent = true" main.go; then
          echo "::set-output name=persistent::true"
        else
          echo "::set-output name=persistent::false"
        fi

    - name: Run tests
      run: |
        if [ "${{ steps.determine-persistent.outputs.persistent }}" = "true" ]; then
          go test -v -tags=persistent ./...
        else
          go test -v $(find . -name "*.go" ! -name "db_test.go")
        fi
